[build]
  base    = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "http://72.60.251.63:8080/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
