name: Deploy Backend to VPS

on:
  push:
    branches:
      - config-vps

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          timeout: 60s
          command_timeout: 30m
          source: "backend/**,README.md,docker-compose.yml" 
          target: "/var/www/html/chall-integrobt"
          rm: false

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          timeout: 60s
          script: |
            cd /var/www/html/chall-integrobt/backend
            
            # Instalar dependencias
            docker run --rm -v $(pwd):/app -w /app composer install --ignore-platform-reqs --no-scripts
            
            if [ ! -f .env ]; then
              cp .env.example .env
            fi

            # Configuraciones maestras para Docker en VPS
            sed -i 's/\${APP_PORT:-80}:80/8080:80/g' docker-compose.yml
            sed -i 's/^DB_HOST=.*/DB_HOST=mysql/' .env
            sed -i 's/^DB_PORT=.*/DB_PORT=3306/' .env
            sed -i 's/^DB_DATABASE=.*/DB_DATABASE=challenge_integrobt/' .env
            sed -i 's/^DB_USERNAME=.*/DB_USERNAME=root/' .env
            sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=Lumberjack123/' .env
            
            # ELIMINAR VOLUMENES VIEJOS (-v) para resetear la contraseña de MySQL
            docker compose down -v --remove-orphans || true
            
            # Levantar de cero
            docker compose up -d --build
            
            echo "Inicializando base de datos limpia (50s)..."
            sleep 50
            
            docker exec backend-laravel.test-1 php artisan key:generate || true
            docker exec backend-laravel.test-1 php artisan migrate:fresh --seed
